In [1]:
import numpy as np

In [25]:
x = np.random.randint(1,100,(10,10))

In [14]:
def sigmoid(y):
    return 1/(y**3) + 3/(y**4) + 6/(4*y)

In [15]:
obj = np.vectorize(sigmoid)

In [21]:
obj(x)

array([[0.02027284, 0.01630567, 0.03949335, ..., 0.1513    , 0.11594482,
        0.05775577],
       [0.06007168, 0.01785889, 0.03000848, ..., 0.02727907, 0.01704697,
        0.02344149],
       [0.07514375, 0.04842391, 0.02027284, ..., 0.01666808, 0.16849566,
        0.01546505],
       ...,
       [0.02112967, 0.01515258, 0.04690838, ..., 0.02273091, 0.02381371,
        0.04414533],
       [0.06258138, 0.01764874, 0.02542885, ..., 0.07911618, 0.02586746,
        0.3128    ],
       [0.03192514, 0.01764874, 0.06258138, ..., 0.02941975, 0.02381371,
        0.03062127]])

In [29]:
np.linalg.eig(x)

(array([514.85591415  +0.j        , -20.83003804+102.21310303j,
        -20.83003804-102.21310303j, -58.05596381  +0.j        ,
         52.48983552  +0.j        ,  38.81791836 +29.22421004j,
         38.81791836 -29.22421004j, -17.92692393 +44.6445369j ,
        -17.92692393 -44.6445369j ,  -7.41169863  +0.j        ]),
 array([[-0.25238365+0.j        ,  0.04410809+0.39158336j,
          0.04410809-0.39158336j, -0.30782896+0.j        ,
          0.43938267+0.j        , -0.28429296-0.07269401j,
         -0.28429296+0.07269401j, -0.16797068-0.19738744j,
         -0.16797068+0.19738744j,  0.14655662+0.j        ],
        [-0.26399062+0.j        , -0.40116584+0.01469059j,
         -0.40116584-0.01469059j, -0.10308799+0.j        ,
         -0.58227892+0.j        ,  0.04967337+0.22480589j,
          0.04967337-0.22480589j,  0.17693817-0.04927031j,
          0.17693817+0.04927031j, -0.6342907 +0.j        ],
        [-0.32698395+0.j        ,  0.09657182-0.10598661j,
          0.09657182+0.1059