In [1]:
import numpy as np

In [2]:
x = np.random.randint(1,100,(5,5))

In [10]:
x

array([[40, 40, 55, 72, 14],
       [32, 86, 92, 55, 70],
       [64, 85, 37, 98, 24],
       [97, 10, 35, 16, 82],
       [57,  7, 20, 79, 74]])

In [7]:
x[0:3,0:2]

array([[40, 40],
       [32, 86],
       [64, 85]])

In [9]:
x[being_row:ending_row , begin_col:ending_col]

array([[40, 40, 55, 72, 14],
       [32, 86, 92, 55, 70]])

In [16]:
for i in x[:,0:4]:
    print(i)

[40 40 55 72]
[32 86 92 55]
[64 85 37 98]
[97 10 35 16]
[57  7 20 79]


In [21]:
x = np.random.randint(1,100,(10,10))

In [22]:
x

array([[99,  7, 30, 98, 95, 49, 51, 78, 37, 19],
       [85, 67, 90, 53, 79,  3, 16,  1, 40,  4],
       [66, 45, 89, 28, 15,  7, 25, 42, 73, 76],
       [66, 99, 99, 93, 60,  8, 99, 66, 20, 25],
       [30, 77,  5, 91, 42,  6, 36, 24, 35, 86],
       [17, 84, 96, 23, 59, 82, 68, 26, 81, 14],
       [23, 26, 22, 63, 19, 27, 81, 51, 26, 92],
       [35, 72, 61, 42, 40, 37,  5, 95, 69, 80],
       [ 7, 97, 80, 19, 96,  5, 77, 87, 73, 53],
       [63, 27,  1, 87, 19, 38,  2, 70, 72, 54]])

In [28]:
x[0:5,begin_point::stepping_size]

array([[99, 30, 95, 51, 37],
       [85, 90, 79, 16, 40],
       [66, 89, 15, 25, 73],
       [66, 99, 60, 99, 20],
       [30,  5, 42, 36, 35]])

In [33]:
x = np.random.randint(1,100,(10,5))

In [32]:
x.reshape(2,25)

array([[28,  8, 51, 55, 34, 11, 22, 60, 44, 86, 16, 39, 48, 23, 75, 83,
         9, 95, 30, 54, 87, 85, 46, 80, 80],
       [69, 87, 30, 62, 48, 96,  7, 54, 56, 20, 84, 32, 52, 25,  8, 27,
        46, 60, 81, 62, 83, 40, 77, 25, 29]])

In [39]:
x

array([[55, 64, 16, 78, 71],
       [21, 22,  7, 36, 81],
       [70, 95, 89,  1, 66],
       [34, 22, 97, 26, 78],
       [99, 29, 82, 87, 85],
       [61, 10, 53, 20, 29],
       [61, 52, 71, 63, 54],
       [33, 76, 88, 93, 70],
       [49, 53, 59, 90, 56],
       [10, 41, 22, 41, 15]])

In [40]:
np.vstack((x,x))

array([[55, 64, 16, 78, 71],
       [21, 22,  7, 36, 81],
       [70, 95, 89,  1, 66],
       [34, 22, 97, 26, 78],
       [99, 29, 82, 87, 85],
       [61, 10, 53, 20, 29],
       [61, 52, 71, 63, 54],
       [33, 76, 88, 93, 70],
       [49, 53, 59, 90, 56],
       [10, 41, 22, 41, 15],
       [55, 64, 16, 78, 71],
       [21, 22,  7, 36, 81],
       [70, 95, 89,  1, 66],
       [34, 22, 97, 26, 78],
       [99, 29, 82, 87, 85],
       [61, 10, 53, 20, 29],
       [61, 52, 71, 63, 54],
       [33, 76, 88, 93, 70],
       [49, 53, 59, 90, 56],
       [10, 41, 22, 41, 15]])

In [41]:
x = np.random.randint(1,10,(10000,10000))

In [47]:
x ** 3

array([[729, 512, 343, ..., 125,   8, 216],
       [512, 343, 125, ..., 512,  64, 216],
       [512,   1,   1, ...,   1,  27,  27],
       ...,
       [ 64,  64, 729, ...,   1, 729,   1],
       [729, 729, 216, ...,   8, 512, 343],
       [216,   8,  64, ..., 512,  64, 125]], dtype=int32)

In [48]:
for i in range(10000):
    for j in range(10000):
        x[i,j] = x[i,j] ** 3