## Numpy and pandas assignment.

### Numpy questions

In [1]:
# Import pandas and numpy. Code here..!


In [2]:
# create a numpy array with shape 5 X 5


In [3]:
# print numpy shape, dtype, itemsize, ndim


In [4]:
# print first 2 rows and 2 column from numpy array


In [5]:
# create numpy array with random integers and shape 10,10


In [6]:
# reshape 5x5 numpy array into 10 X 5 array


In [7]:
# stack two numpy array together horizantally or vertically


In [8]:
# perform any operation between two numpy arrays ex, addition, dot product 


In [9]:
# perform any linear algebra operation ex determinant, eigen value, inverse


In [10]:
# delete first 2 rows from a 2d numpy array


### Pandas questions

In [11]:
# create a pandas dataframe and pandas series 


In [12]:
# import the csv file attached with the python notebook


In [13]:
# print shape,info,column names and first 5 rows


In [14]:
# select rows from 3 to 10 and columns from 5 to 20


In [15]:
# make any column as index 


In [16]:
# concat dataframes one upon the other ( you can use same dataframe twice )


In [17]:
# merge two dataframes upon some identical column ( you can use same dataframe )


In [18]:
# Use conditional selection to select few rows. ( condition is your choice )


In [19]:
# demonstrate difference between location based and index based selection


In [20]:
# convert a dataframe into numpy array and convert backto dataframe


In [51]:
import numpy as np

grid = np.random.randint(0,2,(10,10))

def fun(x):
    if x == 1:
        return 'T'
    if x == 0:
        return 'W'
    
con = np.vectorize(fun)
grid = con(grid)

#print(grid)

selection = 'invalid'
while selection == 'invalid':
    random_selection = np.random.randint(0,5,(1,2))[0]
    if grid[random_selection[0],random_selection[1]] == 'T':
        selection = 'valid'
    


x=5
y=5
grid[x,y]=0

def spread(grid,x,y):
    grid[x,y]=0
    if x-1 >= 0 and x-1 <= 10 and y-1 >= 0 and y-1 <= 10: #--
        try:
            grid[x-1,y-1]=0
        except:
            pass
    if x+1 >= 0 and x+1 <= 10 and y+1 >= 0 and y+1 <= 10: #++
        try:
            grid[x+1,y+1]=0
        except:
            pass
    if x+1 >= 0 and x+1 <= 10 and y-1 >= 0 and y-1 <= 10: #+-
        try:
            grid[x+1,y-1]=0
        except:
            pass
    if x-1 >= 0 and x-1 <= 10 and y+1 >= 0 and y+1 <= 10: #_+
        try:
            grid[x-1,y+1]=0
        except:
            pass
    if x-1 >= 0 and x-1 <= 10 and y >= 0 and y <= 10: #-
        try:
            grid[x-1,y]=0
        except:
            pass
    if x >= 0 and x <= 10 and y-1 >= 0 and y-1 <= 10: # -
        try:
            grid[x,y-1]=0
        except:
            pass
    if x+1 >= 0 and x+1 <= 10 and y >= 0 and y <= 10: #+
        try:
            grid[x+1,y]=0
        except:
            pass
    if x >= 0 and x <= 10 and y+1 >= 0 and y+1 <= 10:
        try:
            grid[x,y+1]=0
        except:
            pass
    return grid
        
grid = np.random.randint(1,2,(10,10))       
grid = spread(grid,x,y)
for i in range(grid.shape[0]):
    for j in range(grid.shape[1]):
        if grid[i,j]==0:
            spread(grid,i,j)
            
            
print(grid)            
        


    
    

    

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
