In [1]:
import numpy as np

In [2]:
A = np.random.randint(1,10,(5,5))
B = np.random.randint(1,10,(5,5))
C = np.random.randint(1,10,(5,5))

In [3]:
r , s = 5 , 4

In [4]:
zero = np.zeros((5,5))

In [5]:
(A + B) == (B + A)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [6]:
(A + B) + C == A + (B + C)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [7]:
A + zero == A

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [8]:
r * (A +B) == r*A + r*B

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [9]:
r * (s * A) == (r * s) * A

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [10]:
(A * B) * C == A * (B * C)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [11]:
A * (B + C) == A*B + A*C

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [12]:
r * ( A * B) == (r * A) * B

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [13]:
r * ( A * B) == A * (r * B)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [14]:
I = np.eye(5)

In [15]:
np.dot(A,I) == A

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [19]:
A.T.T == A

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [20]:
(A +B).T == A.T + B.T

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [21]:
(r*A).T == r*A.T

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [22]:
(A*B).T == A.T * B.T

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [24]:
I.T == I

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [33]:
np.log(r) * np.linalg.inv(A) == np.linalg.inv(r*A)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [35]:
A * np.linalg.inv(A) ==  np.linalg.inv(A) * A

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [37]:
np.linalg.inv((A*B)) == np.linalg.inv(B) * np.linalg.inv(A)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [39]:
np.linalg.inv(I) == I

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [40]:
np.linalg.inv(A.T) == np.linalg.inv(A).T

array([[False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [False, False,  True,  True, False],
       [False, False, False,  True, False]])

In [44]:
np.linalg.inv(np.linalg.inv(A))

array([[2., 2., 9., 3., 1.],
       [5., 2., 2., 8., 3.],
       [9., 9., 9., 8., 6.],
       [2., 7., 4., 9., 9.],
       [5., 6., 7., 4., 7.]])

In [51]:
x = np.arange(1,10,.1)

In [55]:
def fun(x):
    return x-1


[i for i  in map(fun,x)]

[0.0,
 0.10000000000000009,
 0.20000000000000018,
 0.30000000000000027,
 0.40000000000000036,
 0.5000000000000004,
 0.6000000000000005,
 0.7000000000000006,
 0.8000000000000007,
 0.9000000000000008,
 1.0000000000000009,
 1.100000000000001,
 1.200000000000001,
 1.3000000000000012,
 1.4000000000000012,
 1.5000000000000013,
 1.6000000000000014,
 1.7000000000000015,
 1.8000000000000016,
 1.9000000000000017,
 2.0000000000000018,
 2.100000000000002,
 2.200000000000002,
 2.300000000000002,
 2.400000000000002,
 2.500000000000002,
 2.6000000000000023,
 2.7000000000000024,
 2.8000000000000025,
 2.9000000000000026,
 3.0000000000000027,
 3.100000000000003,
 3.200000000000003,
 3.3000000000000025,
 3.400000000000003,
 3.5000000000000036,
 3.600000000000003,
 3.700000000000003,
 3.8000000000000034,
 3.900000000000004,
 4.0000000000000036,
 4.100000000000003,
 4.200000000000004,
 4.300000000000004,
 4.400000000000004,
 4.5000000000000036,
 4.600000000000004,
 4.700000000000005,
 4.800000000000004,
 4