In [1]:
import numpy as np

In [2]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [3]:
np.arange(101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [4]:
x = np.array([23,45])

np.tile(x,10)

array([23, 45, 23, 45, 23, 45, 23, 45, 23, 45, 23, 45, 23, 45, 23, 45, 23,
       45, 23, 45])

In [7]:
a = np.random.randint(1,100,(5,10))

In [11]:
a

array([[99, 47, 91, 59, 37, 67, 10, 87, 39, 47],
       [12, 61, 23, 77, 42, 81, 89, 99, 80, 54],
       [56, 58, 25, 83, 53, 49, 35,  5, 35, 61],
       [56,  2, 94, 85,  7, 89, 18, 50, 15, 33],
       [67, 61, 63, 94, 38, 46,  3, 66,  8, 89]])

In [10]:
a.reshape((25,2))

array([[99, 47],
       [91, 59],
       [37, 67],
       [10, 87],
       [39, 47],
       [12, 61],
       [23, 77],
       [42, 81],
       [89, 99],
       [80, 54],
       [56, 58],
       [25, 83],
       [53, 49],
       [35,  5],
       [35, 61],
       [56,  2],
       [94, 85],
       [ 7, 89],
       [18, 50],
       [15, 33],
       [67, 61],
       [63, 94],
       [38, 46],
       [ 3, 66],
       [ 8, 89]])

In [13]:
np.hstack((a,a))

array([[99, 47, 91, 59, 37, 67, 10, 87, 39, 47, 99, 47, 91, 59, 37, 67,
        10, 87, 39, 47],
       [12, 61, 23, 77, 42, 81, 89, 99, 80, 54, 12, 61, 23, 77, 42, 81,
        89, 99, 80, 54],
       [56, 58, 25, 83, 53, 49, 35,  5, 35, 61, 56, 58, 25, 83, 53, 49,
        35,  5, 35, 61],
       [56,  2, 94, 85,  7, 89, 18, 50, 15, 33, 56,  2, 94, 85,  7, 89,
        18, 50, 15, 33],
       [67, 61, 63, 94, 38, 46,  3, 66,  8, 89, 67, 61, 63, 94, 38, 46,
         3, 66,  8, 89]])

In [14]:
np.vstack((a,a))

array([[99, 47, 91, 59, 37, 67, 10, 87, 39, 47],
       [12, 61, 23, 77, 42, 81, 89, 99, 80, 54],
       [56, 58, 25, 83, 53, 49, 35,  5, 35, 61],
       [56,  2, 94, 85,  7, 89, 18, 50, 15, 33],
       [67, 61, 63, 94, 38, 46,  3, 66,  8, 89],
       [99, 47, 91, 59, 37, 67, 10, 87, 39, 47],
       [12, 61, 23, 77, 42, 81, 89, 99, 80, 54],
       [56, 58, 25, 83, 53, 49, 35,  5, 35, 61],
       [56,  2, 94, 85,  7, 89, 18, 50, 15, 33],
       [67, 61, 63, 94, 38, 46,  3, 66,  8, 89]])

## Operations

In [15]:
x = 45


array([[99, 47, 91, 59, 37, 67, 10, 87, 39, 47],
       [12, 61, 23, 77, 42, 81, 89, 99, 80, 54],
       [56, 58, 25, 83, 53, 49, 35,  5, 35, 61],
       [56,  2, 94, 85,  7, 89, 18, 50, 15, 33],
       [67, 61, 63, 94, 38, 46,  3, 66,  8, 89]])

In [44]:
a - a

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [47]:
np.array((a,a)) - a

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]])

In [59]:
np.log(a)

array([[4.59511985, 3.8501476 , 4.51085951, 4.07753744, 3.61091791,
        4.20469262, 2.30258509, 4.46590812, 3.66356165, 3.8501476 ],
       [2.48490665, 4.11087386, 3.13549422, 4.34380542, 3.73766962,
        4.39444915, 4.48863637, 4.59511985, 4.38202663, 3.98898405],
       [4.02535169, 4.06044301, 3.21887582, 4.41884061, 3.97029191,
        3.8918203 , 3.55534806, 1.60943791, 3.55534806, 4.11087386],
       [4.02535169, 0.69314718, 4.54329478, 4.44265126, 1.94591015,
        4.48863637, 2.89037176, 3.91202301, 2.7080502 , 3.49650756],
       [4.20469262, 4.11087386, 4.14313473, 4.54329478, 3.63758616,
        3.8286414 , 1.09861229, 4.18965474, 2.07944154, 4.48863637]])

In [63]:
np.sqrt(a)

array([[9.94987437, 6.8556546 , 9.53939201, 7.68114575, 6.08276253,
        8.18535277, 3.16227766, 9.32737905, 6.244998  , 6.8556546 ],
       [3.46410162, 7.81024968, 4.79583152, 8.77496439, 6.4807407 ,
        9.        , 9.43398113, 9.94987437, 8.94427191, 7.34846923],
       [7.48331477, 7.61577311, 5.        , 9.11043358, 7.28010989,
        7.        , 5.91607978, 2.23606798, 5.91607978, 7.81024968],
       [7.48331477, 1.41421356, 9.69535971, 9.21954446, 2.64575131,
        9.43398113, 4.24264069, 7.07106781, 3.87298335, 5.74456265],
       [8.18535277, 7.81024968, 7.93725393, 9.69535971, 6.164414  ,
        6.78232998, 1.73205081, 8.1240384 , 2.82842712, 9.43398113]])

In [68]:
def fun(x):
    return (x + 3)/np.sqrt(4) + 34
    
name = np.vectorize(fun)

name(a)

array([[85. , 59. , 81. , 65. , 54. , 69. , 40.5, 79. , 55. , 59. ],
       [41.5, 66. , 47. , 74. , 56.5, 76. , 80. , 85. , 75.5, 62.5],
       [63.5, 64.5, 48. , 77. , 62. , 60. , 53. , 38. , 53. , 66. ],
       [63.5, 36.5, 82.5, 78. , 39. , 80. , 44.5, 60.5, 43. , 52. ],
       [69. , 66. , 67. , 82.5, 54.5, 58.5, 37. , 68.5, 39.5, 80. ]])

In [71]:
a = np.random.randint(1,10,(5,5))

In [72]:
np.linalg.det(a)

-200.00000000000028

In [73]:
np.linalg.inv(a)

array([[ 0.6 ,  2.8 , -3.4 , -0.2 ,  0.6 ],
       [ 0.49,  2.12, -2.36, -0.08,  0.19],
       [-1.11, -4.18,  5.04,  0.12, -0.41],
       [ 0.52,  1.76, -2.28,  0.16,  0.12],
       [-0.86, -4.18,  5.04,  0.12, -0.66]])

In [81]:
%%time
np.linalg.eig(a)


Wall time: 0 ns


(array([23.72672121, -2.30099136,  0.13774031,  6.01469113,  4.42183871]),
 array([[ 0.55219951,  0.67878575,  0.37090133,  0.64071954, -0.48177713],
        [ 0.29167849, -0.00210025,  0.28843895, -0.28673383,  0.07764594],
        [ 0.40023066,  0.08468079, -0.60708409, -0.05442488, -0.08917419],
        [ 0.41063666, -0.11740604,  0.28390402, -0.61031183,  0.81651881],
        [ 0.5302757 , -0.71992394, -0.57452815,  0.36306967, -0.29530814]]))