In [1]:
import numpy as np

In [15]:
scalar = 23
vector = np.arange(0,5,(1))
matrix = np.random.random((5,5))
tensor = np.random.randint(1,10,(5,5,5))

In [7]:
scalar * vector

array([ 46. ,  48.3,  50.6,  52.9,  55.2,  57.5,  59.8,  62.1,  64.4,
        66.7,  69. ,  71.3,  73.6,  75.9,  78.2,  80.5,  82.8,  85.1,
        87.4,  89.7,  92. ,  94.3,  96.6,  98.9, 101.2, 103.5, 105.8,
       108.1, 110.4, 112.7])

In [11]:
scalar / matrix

array([[  31.24308424,   39.81908129,  181.66604867,   63.42746815,
         134.4103492 ],
       [  23.449271  ,   60.4930758 ,   67.29980418,   60.72145141,
          36.88355752],
       [  48.64752916,  126.99813818, 1435.46712703,   72.952211  ,
          29.37992708],
       [  30.25285513,  212.20383086,   70.12810114,   28.00078031,
          58.50103159],
       [ 392.13117492,  687.82817812,  353.83530842,   34.21931436,
          24.78893042]])

In [12]:
scalar + tensor

array([[[31, 29, 32, 32, 30],
        [25, 28, 32, 25, 25],
        [31, 25, 27, 30, 31],
        [29, 28, 31, 27, 29],
        [26, 30, 28, 28, 32]],

       [[30, 25, 31, 26, 25],
        [30, 31, 25, 31, 26],
        [28, 24, 31, 27, 24],
        [24, 30, 25, 32, 29],
        [25, 28, 30, 27, 31]],

       [[30, 28, 24, 27, 28],
        [31, 32, 29, 24, 29],
        [25, 29, 26, 24, 26],
        [32, 29, 30, 29, 32],
        [32, 26, 24, 31, 27]],

       [[24, 27, 31, 29, 26],
        [30, 24, 25, 30, 31],
        [30, 32, 28, 25, 29],
        [24, 28, 27, 25, 30],
        [28, 30, 30, 28, 28]],

       [[28, 29, 27, 31, 28],
        [32, 30, 30, 25, 27],
        [26, 26, 27, 30, 28],
        [29, 24, 27, 32, 28],
        [26, 25, 24, 32, 24]]])

In [16]:
vector * matrix

array([[0.        , 0.0616568 , 1.29471986, 2.96392325, 2.90563021],
       [0.        , 0.15686251, 0.95902495, 2.81260848, 1.90324665],
       [0.        , 0.65548642, 0.71112253, 1.60783479, 3.28562348],
       [0.        , 0.8978599 , 1.21848377, 2.30884903, 1.67042853],
       [0.        , 0.93483213, 0.63918659, 1.6494374 , 0.30833269]])

In [19]:
vector * tensor

array([[[ 0,  5, 14, 12,  4],
        [ 0,  3, 18,  6, 36],
        [ 0,  1, 18,  9, 12],
        [ 0,  6, 10, 15, 36],
        [ 0,  2,  8,  9, 24]],

       [[ 0,  9, 10, 27, 28],
        [ 0,  5, 16,  9, 32],
        [ 0,  6,  2, 18, 32],
        [ 0,  5, 16,  6,  8],
        [ 0,  4, 14,  6, 20]],

       [[ 0,  9,  6,  6, 32],
        [ 0,  4, 16, 24, 12],
        [ 0,  5,  2,  9, 24],
        [ 0,  1, 10,  9, 20],
        [ 0,  5,  4, 27, 32]],

       [[ 0,  9,  2, 27,  4],
        [ 0,  8,  2,  9, 12],
        [ 0,  3, 16,  9, 32],
        [ 0,  8, 10, 27, 36],
        [ 0,  3, 16, 27,  8]],

       [[ 0,  8, 14, 24,  8],
        [ 0,  2,  2, 27,  8],
        [ 0,  3, 10, 24, 20],
        [ 0,  8, 12, 27, 36],
        [ 0,  6, 12, 27, 24]]])

In [21]:
matrix // tensor

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])