In [2]:
import numpy as np

In [15]:
x = np.random.random((5000,5000))
#25000000

In [18]:
%%time
def fun(x):
    return x**2 + 3 + 5 + 3 ** 2

y = np.vectorize(fun)

y(x)


Wall time: 11.6 s


array([[17.0219621 , 17.36441174, 17.09376462, ..., 17.28168277,
        17.89489128, 17.38571014],
       [17.94486806, 17.30252519, 17.09596835, ..., 17.15458937,
        17.82514904, 17.46859011],
       [17.9030571 , 17.47941233, 17.968371  , ..., 17.1285524 ,
        17.22230746, 17.01153544],
       ...,
       [17.00352716, 17.82876958, 17.01282427, ..., 17.05767927,
        17.79000452, 17.00048477],
       [17.72871174, 17.55823039, 17.11154825, ..., 17.62389899,
        17.78617714, 17.6095419 ],
       [17.00939959, 17.04743722, 17.40809847, ..., 17.86529551,
        17.27480318, 17.20050918]])

In [6]:
np.sin(x)

array([[0.76199803, 0.63086608, 0.71111022, 0.14480195, 0.64575514],
       [0.41257972, 0.58905961, 0.68720543, 0.76952134, 0.68968106],
       [0.81674657, 0.82911885, 0.68214412, 0.61276536, 0.05651543],
       [0.24068861, 0.18296172, 0.36647398, 0.4791361 , 0.40861523],
       [0.58736523, 0.34914779, 0.3733136 , 0.73358539, 0.06883037]])

In [7]:
np.cos(x)

array([[0.64757934, 0.77589174, 0.70308055, 0.98946066, 0.76354456],
       [0.9109215 , 0.80808958, 0.72646314, 0.6386211 , 0.72411327],
       [0.57699656, 0.55907238, 0.73121775, 0.7902649 , 0.99840173],
       [0.97060239, 0.98312004, 0.9304283 , 0.87774062, 0.91270674],
       [0.80932199, 0.93706767, 0.92770521, 0.67959729, 0.99762838]])

In [8]:
np.exp(x)

array([[2.37831659, 1.97915293, 2.20576862, 1.15640125, 2.01780819],
       [1.53002525, 1.87741274, 2.1332256 , 2.40630238, 2.14051939],
       [2.60061967, 2.65788249, 2.11846315, 1.93393184, 1.05817482],
       [1.27516458, 1.20201364, 1.45530647, 1.64817764, 1.52338729],
       [1.87348335, 1.42855223, 1.46605964, 2.27864916, 1.07131282]])

In [9]:
np.linalg.det(x)

-0.01186685859999639

In [10]:
np.linalg.inv(x)

array([[  1.95840595,   0.50921052,  -2.14754038,  -4.47902329,
          3.5488127 ],
       [  1.00787305,   6.22482258,  -2.31720659, -13.11457295,
          2.99771653],
       [ -3.57283599, -10.22702092,   8.0611457 ,  25.01893189,
        -10.10043997],
       [ -0.44916783,   1.28404211,  -0.76778979,  -1.7292444 ,
          1.58844419],
       [  2.14649086,   4.57697943,  -4.02117227,  -9.55409797,
          3.75817072]])

In [11]:
np.linalg.eig(x)

(array([ 2.85321668+0.j        , -0.61538146+0.j        ,
         0.25386274+0.17928368j,  0.25386274-0.17928368j,
         0.0699728 +0.j        ]),
 array([[-0.52632423+0.j        ,  0.37336724+0.j        ,
         -0.5337999 +0.05225894j, -0.5337999 -0.05225894j,
          0.23764111+0.j        ],
        [-0.49791068+0.j        ,  0.3809619 +0.j        ,
          0.56719779+0.j        ,  0.56719779-0.j        ,
          0.26560833+0.j        ],
        [-0.55516095+0.j        , -0.63723737+0.j        ,
         -0.06519128-0.47281078j, -0.06519128+0.47281078j,
         -0.83967194+0.j        ],
        [-0.24080695+0.j        ,  0.25649686+0.j        ,
          0.11474163+0.23683112j,  0.11474163-0.23683112j,
          0.09440566+0.j        ],
        [-0.32996377+0.j        , -0.49356137+0.j        ,
         -0.04944519+0.30185087j, -0.04944519-0.30185087j,
          0.39877   +0.j        ]]))