In [2]:
import numpy as np

In [7]:
np.array([[[[2,2,3,4,5,7],[2,2,3,4,5,7]],[[2,2,3,4,5,7],[2,2,3,4,5,7]]],[[[2,2,3,4,5,7],[2,2,3,4,5,7]],[[2,2,3,4,5,7],[2,2,3,4,5,7]]]])

array([[[[2, 2, 3, 4, 5, 7],
         [2, 2, 3, 4, 5, 7]],

        [[2, 2, 3, 4, 5, 7],
         [2, 2, 3, 4, 5, 7]]],


       [[[2, 2, 3, 4, 5, 7],
         [2, 2, 3, 4, 5, 7]],

        [[2, 2, 3, 4, 5, 7],
         [2, 2, 3, 4, 5, 7]]]])

In [14]:
np.zeros((2,10,5,2,3,4,6))

array([[[[[[[0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0.]],

           [[0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0.]],

           [[0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0.]]],


          [[[0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0.]],

           [[0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0.]],

           [[0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0., 0.]]]],



         [[[[0., 0., 0., 0., 0., 0.],
            [0., 0., 0., 0., 0.,

In [21]:
np.arange(0,10,.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09,
       1.1 , 1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 ,
       1.21, 1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31,
       1.32, 1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42,
       1.43, 1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.

In [25]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [27]:
np.random.random((5,5,5))

array([[[0.46586947, 0.36067265, 0.81471574, 0.67082016, 0.91214708],
        [0.88203477, 0.18758527, 0.87434093, 0.91117383, 0.95931133],
        [0.45923822, 0.20883597, 0.21924255, 0.49374558, 0.91493982],
        [0.91752356, 0.64087807, 0.90106233, 0.60827967, 0.00802101],
        [0.74583785, 0.5023647 , 0.29466615, 0.73498106, 0.14412673]],

       [[0.4463174 , 0.6192476 , 0.15825806, 0.60579552, 0.6770368 ],
        [0.13605006, 0.45140422, 0.55977372, 0.41204433, 0.78993845],
        [0.86891717, 0.95994835, 0.99125033, 0.59321991, 0.67344413],
        [0.3641933 , 0.99659924, 0.62096016, 0.54849399, 0.33704411],
        [0.0137158 , 0.68538526, 0.99872039, 0.67686983, 0.20515052]],

       [[0.4666299 , 0.93937774, 0.28845582, 0.49118873, 0.38581507],
        [0.52231395, 0.58141797, 0.25270821, 0.61902442, 0.1315033 ],
        [0.98702392, 0.59905071, 0.07776021, 0.42396982, 0.77943766],
        [0.3687749 , 0.13396629, 0.31849406, 0.33291552, 0.93788984],
        [0.14406

In [28]:
np.random.randint(1,10,(5,5))

array([[6, 4, 9, 4, 5],
       [5, 9, 2, 1, 7],
       [2, 8, 6, 2, 1],
       [3, 8, 7, 2, 8],
       [5, 1, 9, 7, 6]])

In [29]:
import pandas as pd

In [44]:
np.tile([2,0],(2,2))

array([[2, 0, 2, 0],
       [2, 0, 2, 0]])

In [69]:
%%time
np.random.randint(1,10,(10000,10000)) * np.random.randint(1,10,(10000,10000))

Wall time: 4.53 s


array([[ 4, 16, 16, ...,  3, 16, 54],
       [18, 56, 30, ..., 24, 72, 42],
       [54, 48, 40, ..., 81, 21, 16],
       ...,
       [ 9, 36, 18, ...,  9, 15,  6],
       [16,  7,  8, ..., 56, 16, 40],
       [10, 24,  3, ..., 36, 25, 16]])